= E-INK for micropython

== Intro


This repo mainly focuses on the Waveshare 2.9inch Black/white/Red Paper display over an SPI bus. It fixes some issues from the original repo and mainly splits the E-Paper display part and the Framebuffer goodies.

Although it should work with an ESP8266, my initial tests showed issues due to the limited amount of memory. Most of my tests are based on the ESP32.

== Acknowledge

Many thanks to the authors of the following:
- https://github.com/mcauser/micropython-waveshare-epaper
- https://github.com/adafruit/micropython-adafruit-bitmap-font/releases

== Usage

I recommend using ampy: https://github.com/adafruit/ampy

You will probably want to add the following to your `.bash_profile`:
	echo "export AMPY_PORT=/dev/cu.SLAB_USBtoUART" >> ~/.bash_profile
	echo "export AMPY_BAUD=115200" >> ~/.bash_profile
	source ~/.bash_profile

First you need to bring the modules to your ESP32:

	ampy put fbdrawing.py
	ampy put waveshare2in9b.py

This will copy the files on your microcontroller. You can check:

	ampy ls

	$ ampy ls
	waveshare2in9b.py
	fbdrawing.py

If something goes wrong, check your port and baudrate. You may also try to reboot your board. That helps in some cases.

Now using `minicom` or your tool of choice, you may copy/paste (CTRL+E with minicom to switch to paste mode, then CTRL+V to paste and CTRL+D to exit paste mode) one of the samples. Once the sample is loaded, run one of the tests:

	test1()

You can now observe your display.

include::doc/ws2in9b.adoc[]

